name: Bug Report
description: File a bug report
body:
  - type: markdown
    attributes:
      value: |
        ### Prolog
        Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/main/CONTRIBUTING.md).
        
        **Have a question? Need help?**
        Please use [our forum](https://groups.google.com/g/tesseract-ocr).
        
        -----
  - type: textarea
    attributes:
      label: Basic Information
      description: Version info, compiled libraries, SIMD, OpenMP
      placeholder: "Paste the output of the command: tesseract -v"

  - type: markdown
    attributes:
      value: |
        ### Operating System
        Choose the OS where the bug occurs.      
- type: checkboxes
    id: os-windows
    attributes:
      label: Windows
      options:
        - label: Windows 11
        - label: Windows 10
  - type: checkboxes
    id: os-macos
    attributes:
      label: macOS
      options:
        - label: macOS 13 Ventura
        - label: macOS 12 Monterey
        - label: macOS 11 Big Sur
  - type: dropdown
    id: os-linux
    attributes:
      label: Linux
      description: Popular Linux distros with a long time support (LTS)
      multiple: true
      options:
        - Ubuntu 22.04 Jammy
        - Ubuntu 20.04 Focal
        - Debian Testing Bookwarm
        - Debian 11 Bullseye
        - RHEL 9 or RHEL 8 clone: Rocky Linux / AlmaLinux
        - RHEL 8 or RHEL 8 clone: Rocky Linux / AlmaLinux
  - type: textarea
    attributes:
      label: Other Operating System
      placeholder: Enter the name and version of the OS
  - type: textarea
    attributes:
      label: Compiler
      placeholder: "Enter compiler name and version (Examples: MSVC 2019 16.11, Clang 13, GCC 11.1, xcode 12.5.1)" 
  - type: textarea
    attributes:
      label: Virtualization / Containers
      placeholder: "Enter the name and version of the VM / container which you use (Examples: Oracle VM VirtualBox 6.1.26,VMware Workstation 16.1.2, Hyper-V, Docker 20.10.7)"
  - type: textarea
    attributes:
      label: CPU
      placeholder: "Enter your CPU vendor name and model (Examples: Intel Core i7-11700K, AMD Ryzen 7 5800X, Apple Silicon M1)"
  - type: textarea
    attributes:
      label: uname -a
      placeholder: "Paste the output of the command: umame -a (if available in your system)."
  - type: textarea
    attributes:
      label: Current Behavior
  - type: textarea
    attributes:
      label: Expected Behavior
  - type: textarea
    attributes:
      label: Suggested Fix
  - type: textarea
    attributes:
      label: Other Information
      placeholder: Add more details here.
